'use client'
import { store } from "@/redux/store/store";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Provider } from "react-redux";



const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Newsletter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
